version: '3.2'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - '8545:8545'
    command: ganache-cli --networkId 5777 --deterministic --accounts 10 --defaultBalanceEther 10000 --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
